<a href="https://colab.research.google.com/github/DecioVdA/ProveComm/blob/main/TEST_RandomForest_Traffico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

rd_seed = 42

In [27]:

import requests
from io import BytesIO

url = "https://github.com/DecioVdA/ProveComm/raw/refs/heads/main/DataSetAddestramento.xlsx"

response = requests.get(url)
df = pd.read_excel(BytesIO(response.content))

In [28]:
df.head()

,Data,GiornoSettimana,Scolastiche_VDA,Scolastiche_FRA,Scolastiche_CH,Festivo_ITA,Festivo_FRA,Festivo_CH,Dispo_TU,Dispo_Fre,TransitiFRA
0,2024-01-01,Lunedi,1,ABC,nullo,FE,FE,FE,1.0,1.0,2274
1,2024-01-02,Martedi,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,3160
2,2024-01-03,Mercoledi,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,2667
3,2024-01-04,Giovedi,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,2633
4,2024-01-05,Venerdi,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,2608

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             366 non-null    datetime64[ns]
 1   GiornoSettimana  366 non-null    object
 2   Scolastiche_VDA  366 non-null    int64
 3   Scolastiche_FRA  366 non-null    object
 4   Scolastiche_CH   366 non-null    object
 5   Festivo_ITA      366 non-null    object
 6   Festivo_FRA      366 non-null    object
 7   Festivo_CH       366 non-null    object
 8   Dispo_TU         366 non-null    float64
 9   Dispo_Fre        366 non-null    float64
 10  TransitiFRA      366 non-null    int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 31.6+ KB

In [30]:
df['Data'] = pd.to_datetime(df['Data'])
df['Day'] = df['Data'].dt.day # giorno del mese
df['Day_of_week'] = df['Data'].dt.day_of_week
df['Day_of_year'] = df['Data'].dt.day_of_year
df['Month'] = df['Data'].dt.month

In [31]:
df = df.drop(['Data'], axis = 1)
df = df.drop(['GiornoSettimana'], axis = 1)
df

,Scolastiche_VDA,Scolastiche_FRA,Scolastiche_CH,Festivo_ITA,Festivo_FRA,Festivo_CH,Dispo_TU,Dispo_Fre,TransitiFRA,Day,Day_of_week,Day_of_year,Month
0,1,ABC,nullo,FE,FE,FE,1.0,1.0,2274,1,0,1,1
1,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,3160,2,1,2,1
2,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,2667,3,2,3,1
3,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,2633,4,3,4,1
4,1,ABC,nullo,nullo,nullo,nullo,1.0,1.0,2608,5,4,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,1,ABC,GVZ,nullo,nullo,nullo,1.0,1.0,2789,27,4,362,12
362,1,ABC,GVZ,nullo,nullo,nullo,1.0,1.0,3095,28,5,363,12
363,1,ABC,GVZ,nullo,nullo,nullo,1.0,1.0,2673,29,6,364,12
364,1,ABC,GVZ,nullo,nullo,nullo,1.0,1.0,2663,30,0,365,12
365,1,ABC,GVZ,nullo,nullo,nullo,1.0,1.0,1613,31,1,366,12

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Scolastiche_VDA  366 non-null    int64
 1   Scolastiche_FRA  366 non-null    object
 2   Scolastiche_CH   366 non-null    object
 3   Festivo_ITA      366 non-null    object
 4   Festivo_FRA      366 non-null    object
 5   Festivo_CH       366 non-null    object
 6   Dispo_TU         366 non-null    float64
 7   Dispo_Fre        366 non-null    float64
 8   TransitiFRA      366 non-null    int64
 9   Day              366 non-null    int32
 10  Day_of_week      366 non-null    int32
 11  Day_of_year      366 non-null    int32
 12  Month            366 non-null    int32
dtypes: float64(2), int32(4), int64(2), object(5)
memory usage: 31.6+ KB

In [33]:
df['Scolastiche_VDA'] = df['Scolastiche_VDA'].astype(bool)